version: 1.0.0.{build}

branches:
  only:
    - develop
    - /release\/.*/

skip_tags: true
max_jobs: 1
image: Ubuntu1604

build_script:
  - docker build . -t lifescience/blast-wrapper:$APPVEYOR_BUILD_VERSION
  - docker login -u $DOCKER_USER -p $DOCKER_PSWD &> /dev/null
  - docker push lifescience/blast-wrapper:$APPVEYOR_BUILD_VERSION
test: off
